version: '3'

services:
  
  database:
    image: mongo
    container_name: mongo_container
    volumes:
      - ./mongo-volume:/data/database
    ports:
      - 27017:27017
  
  application:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: 12-factor:0.0.4
    deploy:
      replicas: 5
    container_name: 12-factor_container
    environment:
      - MONGO_HOST=database
      - MONGO_PORT=27017
      - MONGO_DB=test
      - PORT=3000
    ports:
      - 3000:3000
